/** @type {import('tailwindcss').Config} */
import { SCREENS } from './responsive';

export default {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      backgroundImage: {
        'top-bar': "url('/src/assets/images/底@3x.webp')",
        'home': "url('/src/assets/images/Group 146@3x.webp')",
        'story': "url('/src/assets/images/Group 144@3x.webp')",
        'message': "url('/src/assets/images/Group 153@3x.webp')",
        'camera': "url('/src/assets/images/Group 148@3x.webp')",
        'top-bg': "url('/src/assets/images/BG.webp')",
        'ribbons': "url('/src/assets/images/彩帶@3x.webp')",
        'pigeon': "url('/src/assets/images/鴿子@3x.webp')",
        'married': "url('/src/assets/images/WERMARRIED@3x.webp')",
        'zhi': "url('/src/assets/images/彥治@3x.webp')",
        'ching': "url('/src/assets/images/陳淨@3x.webp')",
        'bow-tie': "url('/src/assets/images/蝴蝶結@3x.webp')",
        'couple': "url('/src/assets/images/人@3x.webp')",
        'house': "url('/src/assets/images/house@3x.webp')",
        'tree': "url('/src/assets/images/樹@3x.webp')",
        'bike': "url('/src/assets/images/腳踏車@3x.webp')",
        'gress-left': "url('/src/assets/images/L草叢@3x.webp')",
        'gress-right': "url('/src/assets/images/R草叢@3x.webp')",
        'cloud-left': "url('/src/assets/images/L@3x.webp')",
        'cloud-right': "url('/src/assets/images/R@3x.webp')",
        'our-story': "url('/src/assets/images/OUR STORY@3x.webp')",
        'wedding': "url('/src/assets/images/WEDDING@3x.webp')",
        'gallery': "url('/src/assets/images/GALLERY@3x.webp')",
        'line-right': "url('/src/assets/images/R LINE@3x.webp')",
        'line-left': "url('/src/assets/images/L LINE@3x.webp')",
        'flower-left': "url('/src/assets/images/L 花@3x.webp')",
        'flower-right': "url('/src/assets/images/R 花@3x.webp')",
        'flower': "url('/src/assets/images/花@3x.webp')",
        'gress': "url('/src/assets/images/deco1@3x.webp')",
        'when': "url('/src/assets/images/when@3x.webp')",
        'where': "url('/src/assets/images/where@3x.webp')",
        'trunk': "url('/src/assets/images/樹幹@3x.webp')",
        'flower2': "url('/src/assets/images/deco2@3x.webp')",
        'gress2': "url('/src/assets/images/deco3@3x.webp')",
        'asselocation': "url('/src/assets/images/asselocation.svg')",
        'map': "url('/src/assets/images/地圖@3x.webp')",
        'parking-lot1': "url('/src/assets/images/Rectangle86@3x.webp')",
        'parking-lot2': "url('/src/assets/images/Rectangle87@3x.webp')",
        'parking-lot3': "url('/src/assets/images/Rectangle88@3x.webp')",
        'cheers': "url('/src/assets/images/酒@3x.webp')",
        'socks': "url('/src/assets/images/襪子@3x.webp')",
        'phone': "url('/src/assets/images/手機@3x.webp')",
      },
      colors: {
        'content-green': '#526e07',
      },
    },
    screens: SCREENS,
  },
  plugins: [],
};
